name: Release and Deploy
on:
  pull_request:
    types: [closed]
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Retrieve secret file
        run: |
          mkdir ./config
          echo "${{ secrets.CONFIG_JSON }}" > ./config/config.json
          echo "${{ secrets.FIREBASE_JSON }}" > ./config/firebase.json
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/light-novel-backend:latest
            ghcr.io/${{ github.repository_owner }}/light-novel-backend:${{ steps.tag_version.outputs.new_tag }}
      - name: Deploy to Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password : ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            docker stop light-novel-backend || true && docker rm light-novel-backend || true
            docker pull ghcr.io/${{ github.repository_owner }}/light-novel-backend:${{ steps.tag_version.outputs.new_tag }}
            docker run -d --name light-novel-backend ghcr.io/${{ github.repository_owner }}/light-novel-backend:${{ steps.tag_version.outputs.new_tag }}